name: 'Sync Jira Workflow'
description: 'modify jira workflow status'
inputs:
  jira_url:
    description: 'jira url'
    required: true
  jira_user:
      description: 'jira user'
      required: true
  jira_token:
    description: 'jira token'
    required: true
  jira_status_flow:
    description: 'jira status flow'
    required: true
outputs:
  success:
    description: 'modify success'
runs:
  using: 'node16'
  main: 'index.js'
