name: 'Sync Jira Workflow'
description: 'modify jira workflow status'
inputs:
  jira_url:
    description: 'jira url'
    required: true
  jira_user:
      description: 'jira user'
      required: true
  jira_token:
    description: 'jira token'
    required: true
  jira_status:
    description: 'jira status is "In Progress", "To Code Review", "To Inspect"'
    required: true
  action_status:
    description: 'action status is pr_merged, pull_request, new_branch'
    required: true
outputs:
  success:
    description: 'modify success'
runs:
  using: 'node12'
  main: 'index.js'
